name: Publish to server

on:
  push:
    branches: [ "main" ]

jobs:

  push_to_registry:
    name: Publish to server
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Connect and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          port: 22
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script_stop: true
          script: |
            echo "Stop container"
            docker stop ${{ secrets.NAME_PS }}
            docker rm ${{ secrets.NAME_PS }}
            echo "Start frontend container"
            docker run -p 80:80 --name ${{ secrets.NAME_PS }} 
            echo "Finish deploying!"name: Deploy
 

