name: Update Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SCP files to remote server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: .
        target: /usr/share/nginx/html

    - name: SSH to remote server and update code
      uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.SERVER_IP }}
       username: ${{ secrets.SERVER_USERNAME }}
       key: ${{ secrets.DEPLOY_KEY }}
       password: ${{ secrets.GIT_TOKEN }}
       script_stop: true
       script: |
          docker rmi my_nginx_image
          git fetch
          git reset --hard origin/main
          docker build -t my_nginx_image:latest /cbs
          docker restart nginx_container
        
 
