 name: Publish to server

on:
  push:
    branches: [ "main" ]

jobs:

  push_to_registry:
    name: Publish to server
    runs-on: ubuntu-latest
    steps:
      - name: Connect and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          port: 22
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script_stop: true
          script: |
            echo "Stop container"
            docker stop ${{ secrets.NAME_PS }}
            docker rm ${{ secrets.NAME_PS }}
            echo "Start frontend container"
            docker run -p 80:80 --name ${{ secrets.NAME_PS }}
            echo "Finish deploying!"
