name: Publish to server

on:
  push:
    branches: [ "main" ]

jobs:
  server_update:
    name: Update server by ssh
    runs-on: ubuntu-latest

    steps:
      - name: Connect and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          port: 22
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script_stop: true
          script: |
            echo "Stop container"
            docker stop ${{ secrets.NAME_PS }}
            docker rm ${{ secrets.NAME_PS }}
            docker run -p 80:80 --name ${{ secrets.NAME_PS }}
            docker run -d -p 80:80 --name ${{ secrets.NAME_PS }} -v site_volume:/usr/share/nginx/html my_nginx_image
    
