name: Deploy Website

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to remote server
      uses: appleboy/scp-action@master
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }} # добавьте запасной секрет "SERVER_IP" в своем репозитории с IP-адресом удаленного сервера
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }} # добавьте запасной секрет "SERVER_USERNAME" в своем репозитории с именем пользователя удаленного сервера
        SERVER_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }} # добавьте запасной секрет "SERVER_SSH_PRIVATE_KEY" в своем репозитории с приватным ключом SSH удаленного сервера
      with:
        src: "./cbs" # путь к вашему исходному коду в репозитории
        host: ${{ env.SERVER_IP }}
        username: ${{ env.SERVER_USERNAME }}
        key: ${{ env.SERVER_SSH_PRIVATE_KEY }}
        port: 22
        dest: "/var/www/html" # путь к целевой папке на удаленном сервере
