name: Publish to server

on:
  push:
    branches: [ "main" ]

jobs:
  server_update:
    name: Update server by ssh
    runs-on: ubuntu-latest

    steps:
      - name: Connect and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          port: 22
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script_stop: true
          script: bash deploy.sh
