name: Deploy
 
on:
    push:
        tags:
            - main
jobs:
    build:
        runs-on: ubuntu-20.04
        timeout-minutes: 30
        steps:
        
            -   run: ls -la
            -   uses: actions/checkout@master
            -   run: sudo apt update && sudo apt upgrade
 
            -   run: sudo apt-get install rsync
            
            -   name: Deploy theme on server
                id: deploy_theme
                uses: Pendect/action-rsyncer@v1.1.0
                env:
                    DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
                with:
                    port: '22'
                    flags: '-avc --delete'
                    options: ''
                    ssh_options: ''
                    src: '.'
                    dest: 'root@"${{secrets.SERVER_IP}}":/var/www/html'
 
            -   name: Display status from deploy
                run: echo "${{ steps.deploy.outputs.status }}"
