name: Update Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: SCP files to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: .
          target: /path/to/repository/cbs
      
      - name: SSH to remote server and restart container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            docker stop nginx_container
            docker rm nginx_container
            docker run -d --name nginx_container -p 80:80 -v site_volume:/usr/share/nginx/html my_nginx_image


