    name: Deploy to Server

    on:
      push:
        branches:
          - main

    jobs:
      deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Repository
            uses: actions/checkout@v2

          - name: Install rsync
            run: sudo apt-get install rsync -y

          - name: Deploy to Server
            run: |
              rsync -avz --delete ${{ github.workspace }}/ root@46.148.229.230:/path/to/repository/cbs
    
